### ISSUE TITLE
Problema no envio de pageview e eventos

### ISSUE THREAD

**Issue by eduardomrj** [maiconsi/DGoogleAnalytics#1]
Olá,
estive testando sua solução e encontrei um problema,
Ele consegue identificar a aplicação porem eventos não mostra e telas fica (not set)

**Comment by eduardomrj** [comment]
Tem também um problema no DEMO que está faltando um .pas, acho que nome 'GoogleAnalyticsGlobal'

**Comment by maiconsi** [comment]
Desculpe a demora amigo, já adicionei a unit e fiz alguns ajustes na estrutura.

**Comment by maiconsi** [comment]
> Olá,
> estive testando sua solução e encontrei um problema,
> Ele consegue identificar a aplicação porem eventos não mostra e telas fica (not set)

Qual o menu dentro do Google Analytics  que você visualizou essa informação.?
